config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
   resources :comments
  end

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page'
  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'simple_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  validates :name, presence: true
  validates :description, presence: true
  validates :long_description, presence: true
  validates :ingredients, presence: true
  validates :how_to_use, presence: true
  validates :price, presence: true
  validates :image_url, presence: true

  def self.search(search_term)
    if Rails.env.production? # use "ilike" matching operator for postgres to ignore upper- and lower-case
      Product.where("name ilike ?", "%#{search_term}%")
    else
    	Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def authenticate_admin!
    # check if current user is admin
    unless current_user.admin
      # if current_user is not admin redirect to some route
      redirect_to simple_pages_index_path, notice: "You are not authorised to perform that action!"
    end
    # if current_user is admin he will proceed to edit action
  end

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :long_description, :ingredients, :how_to_use, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

app/views/products/_form.html.erb
<section class="container-fluid-form">
<p id="notice"><%= notice %></p>
  <div class="form-main">
    <%= form_with(model: product, local: true) do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row new-product-row1">
        <div class="col-12 form-group">
          <h5><%= form.label :name %></h5>
          <div class="col-12 product-form">
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :description %></h5>
          <div class="col-12 product-form">
            <%= form.text_area :description, rows: "3", class: "form-control" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :long_description %></h5>
          <div class="col-12 product-form">
            <%= form.cktext_area :long_description, rows: "10", class: "form-control" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :ingredients %></h5>
          <div class="col-12 product-form">
            <%= form.cktext_area :ingredients, rows: "3", class: "form-control" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :how_to_use %></h5>
          <div class="col-12 product-form">
            <%= form.cktext_area :how_to_use, rows: "3", class: "form-control" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :price %></h5>
          <div class="col-12 product-form">
            <%= form.text_area :price, rows: "1" %>
          </div>
        </div>

        <div class="col-12 form-group">
          <h5><%= form.label :image_url %></h5>
          <div class="col-12 product-form">
            <%= form.text_field :image_url %>
          </div>
        </div>

      </div> <!-- end row -->

      <div class="actions">
      <p><%= form.submit class:"search-form-button" %></p>
      </div>

    <% end %> <!-- end form do -->
  </div> <!-- end form main -->
</section>

app/views/products/_new_comment.html.erb
<div class="product-new-reviews">
  <% if signed_in? %>
    <div class="row show-comments">
      <div class="col show-comments-col">
        <div class="text-left">
          <p><strong>Add a review</strong></p>
        </div>
        <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
        <div class="md-form">
          <%= f.text_area :body, class: "form-control", placeholder: "Please write your review here", rows: "5" %>
        </div>
        <div class="rating"></div>
        <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 col-xl-3 d-flex align-items-stretch col-product">
  <div class="card">
    <div class="card-body">
      <% cache product do %>
        <%= link_to image_tag(product.image_url, class: "img-fluid product-img"), product_path(product.id) %>
        <h5><%= link_to product.name, product_path(product.id) %></h5>
        <p><%=product.description %></p>
        <strong><%= number_to_currency(product.price, class:"price", unit: "€") %></strong>
        <br>
        <p>
            <% if signed_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_product_path(product), class:"btn btn-warning btn-block" %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-block" %>
            <% end %>
        </p>
      <% end %>  
    </div>
  </div>
</div><!-- /col -->

app/views/products/edit.html.erb
<section class="content-show-product">
  <h1>Editing Product</h1>

  <%= render 'form', product: @product %>
  <br>
  <p><%= link_to 'Show', @product, class:"btn btn-outline-success" %>
  <%= link_to 'Back to products', products_path, class: "btn btn-outline-secondary" %></p>
</section> <!-- end content-show-product -->

app/views/products/index.html.erb
<section class="content-products-overview">
 <p id="notice"><%= notice %></p>
  <header class="products-overview-header">
    <h3>Products</h3>
  </header> <!-- end header -->

  <div class="container-fluid products-overview-main">
    <div class="row products-overview">
      <% cache(cache_key_for_products) do %>
        <%= render @products %>
      <% end %>
    </div> <!-- end row -->
  </div> <!-- end container products-overview -->

    <% if signed_in? && current_user.admin? %>
      <%= link_to 'New Product', new_product_path, class: "btn btn-secondary" %>
    <% end %>

</section> <!-- end section products-overview -->

app/views/products/new.html.erb
<section class="content-new-product">

  <h3>New Product</h3>

  <%= render 'form', product: @product %>
  <br>
  <p><%= link_to 'Back to products', products_path, class: "btn btn-outline-secondary" %></p>

</section>

app/views/products/show.html.erb
<section class="content-show-product">
  <div class="container-fluid show-product-main">
		<div class="row show-product-row" data-product-id="<%= @product.id %>">
      <div class="col-xs-6 col-sm-6 col-lg-4 col-xl-4 show-image-col">
      <% cache @product do %>
        <%= image_tag(@product.image_url, class: "img-fluid product-show-image img-zoom", data_zoom_image: "@product.product_image.url") %>
      </div> <!-- end show-image-col-->
      <div class="col show-product-col">
				<h5><%= @product.name %></h5>
				<div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div>
				<p>
					<strong>Price:</strong>
					<%= number_to_currency(@product.price, unit: "€") %>
				</p>

        <p>
          <%= form_with(url: '/payments/create') do |form| %>
            <%= hidden_field_tag(:product_id, @product.id) %>
            <%= render partial: "shared/stripe_checkout_button" %>
          <% end %>
        </p>

				<p><%= @product.description %></p>

        <p>
	        <strong>Description:</strong>
	        <%= @product.long_description.html_safe %>
	      </p>
        <p>
	        <strong>Ingredients:</strong>
	        <%= @product.ingredients.html_safe %>
	      </p>
	      <p>
	        <strong>How to use:</strong>
	        <%= @product.how_to_use.html_safe  %>
	      </p>
        <% end %>
      </div> <!-- end show-product-col -->
    </div>

			<div class="row show-comments-row">
				<div class="col-xs-6 col-sm-6 col-lg-4 col-xl-4">
					<p><%= render 'new_comment' %></p>
				</div>  <!--end col -->
				<div class="col">
					<br>
					<p><strong>Reviews</strong></p>
          <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
					<p><%= render 'comments' %></p>
					<%= will_paginate @comments %>
					<%= link_to 'Back to products', products_path, class: "btn btn-outline-secondary"%>
        </div>  <!--end col -->
			</div>  <!-- end show-product-row -->

		</div>  <!-- end show-comments-row -->

</section>  <!-- end content-show-product -->