config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }

  resources :products do
   resources :comments
  end

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page'
  root 'simple_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'simple_pages/thank_you'
  post 'payments/create'

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaTz~CreaTionz</title>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!--navbar starts here-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light fixed-top" role="navigation" id="navbar-main">
      <%= link_to image_tag("Website Logo1.jpg", class: "img-responsive logo-image"), simple_pages_landing_page_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> <!-- end button -->

      <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to "Home", simple_pages_index_path, class: "nav-link" %> <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <%= link_to "Products", products_url, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Orders", orders_url, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          </li>
          <% else %>
          <li class="nav-item">
           <%= link_to('Login', new_user_session_path, class: "nav-link") %>
          </li>
          <% end %>
          <li>
            <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
            <%= form.text_field :q, id: 'q', value: params[:q], class: "search-form-field" %>
            <%= form.submit 'Search', class: "search-form-button" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav> <!-- end nav container -->

    <div class="container-notices">
      <% if notice %>
        <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>

    <footer class="footer-section">
      <div class="footer-copyright">
        <p>&copy;Copyright - CaTz~CreaTionz 2019</p>
      </div> <!-- end footer-copyright -->
    </footer> <!-- end footer -->

  </body>
</html>